#声明可以通过url订阅的配置
config-list:
  - name: tcl
    include:
      - "C:\Users\116\Desktop\subtest/rules/bilibili-proxy-rule.yml"
      - "C:\Users\116\Desktop\subtest/providers.yml"
  - name: home
  - name: global
sub-list:
  - name: linghun
    main-proxy-group-name: 灵魂云
    default-proxy-name: MY_PROXY
    request-headers:
      User-Agent: clash
    delivery-headers:
      - Subscription-Userinfo
      - Profile-Web-Page-Url
      - Profile-Update-Interval
    sub-url: https://rsslinghun1.xyz/api/v1/client/subscribe?token=4a30f91d82ecefb2070f8a48c73679c0
  - name: linghun2
    main-proxy-group-name: 灵魂云
    default-proxy-name: MY_PROXY
    request-headers:
      User-Agent: clash
    delivery-headers:
      - Subscription-Userinfo
      - Profile-Web-Page-Url
      - Profile-Update-Interval
    sub-url: https://rsslinghun1.xyz/api/v1/client/subscribe?token=4a30f91d82ecefb2070f8a48c73679c0
  -