config:
  url: https://rsslinghun1.xyz/api/v1/client/subscribe?token=4a30f91d82ecefb2070f8a48c73679c0
  type: clash
  header-names:
    - Subscription-Userinfo
    - Profile-Web-Page-Url
    - Profile-Update-Interval
  subConverter:
    host: 127.0.0.1
    port: 25500

logging: debug