config:
  url: https://rsslinghun1.xyz/api/v1/client/subscribe?token=4a30f91d82ecefb2070f8a48c73679c0
  type: clash
  header-names:
    - Subscription-Userinfo
    - Profile-Web-Page-Url
    - Profile-Update-Interval
  convert-values:
    - location: proxy-groups.name
      type: string
      pattern: xx
      value: MAIN_SELECT
    - location: proxy-groups.proxies.name
      type: string
      pattern: xx
      value: MAIN_SELECT
    - location: rules
      type: regex
      pattern: (?<=,)[^\s,](?=[^\S\n]*[,$])
      value: MAIN_SELECT