mixed-port: 7890
dns:
  enable: false
  ipv6: false
  default-nameserver:
    - "223.5.5.5"
    - "119.29.29.29"
  enhanced-mode: "fake-ip"
  fake-ip-range: "198.18.0.1/16"
  fake-ip-filter:
    - "*.tcl.com"
    - "tcl.com"
    - "*.tclking.com"
    - "tclking.com"
    - "*.msftconnecttest.com"
    - "msftconnecttest.com"
  use-hosts: true
  nameserver:
    - "https://doh.pub/dns-query"
    - "https://dns.alidns.com/dns-query"
  fallback:
    - "https://doh.dns.sb/dns-query"
    - "https://dns.cloudflare.com/dns-query"
    - "https://dns.twnic.tw/dns-query"
    - "tls://8.8.4.4:853"
  fallback-filter:
    geoip: true
    ipcidr:
      - "240.0.0.0/4"
      - "0.0.0.0/32"
bypass:
  - "*.tcl.com"
  - "tcl.com"
  - "*.tclking.com"
  - "tclking.com"
  - "*.msftconnecttest.com"
  - "msftconnecttest.com"
proxies:
  # aws
  - { name: aws, server: 13.35.69.104, port: 443, type: vmess, uuid: a9a6cd6d-dbdb-4b6b-8f0e-d3d81766c170, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: { path: /a9a6cd6d-dbdb-4b6b-8f0e-d3d81766c170, headers: { Host: d1senemq0jpzlo.cloudfront.net } }, udp: true }
  # 45.134.93.165
  - { name: ISP1, type: socks5, server: 45.134.93.165, port: 58169, username: 8Z1iLjM1j8l49IO, password: 7zJ14Hco23Fcvcj, udp: true }
  # 45.134.93.165
  - { name: ISP2, type: socks5, server: 45.134.93.165, port: 58169, username: 8Z1iLjM1j8l49IO, password: 7zJ14Hco23Fcvcj, udp: true }
proxy-groups:
  - name: MY_PROXY
    type: select
    proxies:
      - MODE_SELECT

  - name: MODE_SELECT
    type: select
    proxies:
      - MAIN_SELECT
      - RELAY_TO_ISP
      - ISP_SELECT

  - name: RELAY_TO_ISP
    type: relay
    proxies:
      - MAIN_SELECT
      - ISP_SELECT

  - name: ISP_SELECT
    type: select
    proxies:
      - ISP1
      - ISP2
rules:
  #private custom
  - DOMAIN-SUFFIX,local.cn,DIRECT

  #csdn.net
  - DOMAIN-SUFFIX,csdn.net,MY_PROXY

  #cloudflare
  - DOMAIN-SUFFIX,cloudflare.com,MY_PROXY

  #aws
  - DOMAIN-SUFFIX,awstrack.me,MY_PROXY
  - DOMAIN-SUFFIX,amazon.com,MY_PROXY
  - DOMAIN-SUFFIX,awscloud.com,MY_PROXY

  #tandem
  - DOMAIN-SUFFIX,tandem.net,MY_PROXY

  #microsoft
  - DOMAIN-SUFFIX,microsoft.com,MY_PROXY
  - DOMAIN-SUFFIX,microsoftonline.com,MY_PROXY

  #ipinfo.io query ip
  #- DOMAIN-SUFFIX,ipinfo.io,MY_PROXY

  #must advertising services
  #google ad services
  - DOMAIN-SUFFIX,googleadservices.com,MY_PROXY
  - DOMAIN-SUFFIX,ad.doubleclick.net,MY_PROXY
  - DOMAIN-SUFFIX,pixel.everesttech.net,MY_PROXY

  #shandian
  - DOMAIN-SUFFIX,shandianpro.com,MY_PROXY

  #bing
  - DOMAIN-SUFFIX,bing.com,MY_PROXY

  #oracle
  - DOMAIN-SUFFIX,oracle.com,MY_PROXY

  #postman
  - DOMAIN-SUFFIX,postman.com,MY_PROXY
  - DOMAIN-SUFFIX,getpostman.com,MY_PROXY

  #leetcode
  - DOMAIN-SUFFIX,leetcode.com,MY_PROXY
  - DOMAIN-SUFFIX,leetcode.cn,MY_PROXY

  #chatgpt
  - DOMAIN-SUFFIX,chat.openai.com,MY_PROXY
  - DOMAIN-SUFFIX,openai.com,MY_PROXY

  #tiktok
  - DOMAIN-SUFFIX,tiktokv.com,MY_PROXY
  - DOMAIN-SUFFIX,tiktokcdn.com,MY_PROXY
  - DOMAIN-SUFFIX,tiktokcdn-us.com,MY_PROXY

  #bilibili
  - DOMAIN-SUFFIX,bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,biliapi.net,MY_PROXY
  - DOMAIN-SUFFIX,akamaized.net,MY_PROXY
  - DOMAIN-SUFFIX,bilivideo.com,MY_PROXY
  - DOMAIN-SUFFIX,www.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,s1.hdslb.com,MY_PROXY
  - DOMAIN-SUFFIX,static.hdslb.com,MY_PROXY
  - DOMAIN-SUFFIX,upos-hz-mirrorakam.akamaized.net,MY_PROXY
  - DOMAIN-SUFFIX,data.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,i0.hdslb.com,MY_PROXY
  - DOMAIN-SUFFIX,api.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,api.live.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,i2.hdslb.com,MY_PROXY
  - DOMAIN-SUFFIX,i1.hdslb.com,MY_PROXY
  - DOMAIN-SUFFIX,cm.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,passport.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,api.geetest.com,MY_PROXY
  - DOMAIN-SUFFIX,static.geetest.com,MY_PROXY
  - DOMAIN-SUFFIX,passport.bigfun.cn,MY_PROXY
  - DOMAIN-SUFFIX,passport.biligame.com,MY_PROXY
  - DOMAIN-SUFFIX,passport.bilicomic.com,MY_PROXY
  - DOMAIN-SUFFIX,passport.bigfunapp.cn,MY_PROXY
  - DOMAIN-SUFFIX,passport.bilibili.cn,MY_PROXY
  - DOMAIN-SUFFIX,passport.bilicomics.com,MY_PROXY
  - DOMAIN-SUFFIX,api.vc.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,message.bilibili.com,MY_PROXY
  - DOMAIN-SUFFIX,backup.hdslb.com,MY_PROXY

  #tcl
  - DOMAIN-SUFFIX,tcl.com,DIRECT
  - DOMAIN-SUFFIX,tclking.com,DIRECT

  #默认规则
  #代理优先
  #  - RULE-SET,applications,DIRECT
  #  - DOMAIN,clash.razord.top,DIRECT
  #  - DOMAIN,yacd.haishan.me,DIRECT
  #  - RULE-SET,private,DIRECT
  #  - RULE-SET,reject,REJECT
  #  - RULE-SET,icloud,DIRECT
  #  - RULE-SET,apple,DIRECT
  #  - RULE-SET,google,DIRECT
  #  - RULE-SET,proxy,MY_PROXY
  #  - RULE-SET,direct,DIRECT
  #  - RULE-SET,lancidr,DIRECT
  #  - RULE-SET,cncidr,DIRECT
  #  - RULE-SET,telegramcidr,MY_PROXY
  #  - GEOIP,LAN,DIRECT,no-resolve
  #  - GEOIP,CN,DIRECT,no-resolve
  #  - MATCH,MY_PROXY

  #直连优先
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,MY_PROXY
  - RULE-SET,gfw,MY_PROXY
  - RULE-SET,greatfire,MY_PROXY
  - RULE-SET,telegramcidr,MY_PROXY
  - MATCH,DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400