mixed-port: 7890
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - "223.5.5.5"
    - "119.29.29.29"
  enhanced-mode: "fake-ip"
  fake-ip-range: "198.18.0.1/16"
  fake-ip-filter:
    - "*.tcl.com"
    - "tcl.com"
    - "*.tclking.com"
    - "tclking.com"
    - "*.msftconnecttest.com"
    - "msftconnecttest.com"
  use-hosts: true
  nameserver:
    - "https://doh.pub/dns-query"
    - "https://dns.alidns.com/dns-query"
  fallback:
    - "https://doh.dns.sb/dns-query"
    - "https://dns.cloudflare.com/dns-query"
    - "https://dns.twnic.tw/dns-query"
    - "tls://8.8.4.4:853"
  fallback-filter:
    geoip: true
    ipcidr:
      - "240.0.0.0/4"
      - "0.0.0.0/32"
bypass:
  - "*.tcl.com"
  - "tcl.com"
  - "*.tclking.com"
  - "tclking.com"
  - "*.msftconnecttest.com"
  - "msftconnecttest.com"
proxies:
  - { name: ISP1, type: socks5, server: 45.134.93.165, port: 58169, username: 8Z1iLjM1j8l49IO, password: 7zJ14Hco23Fcvcj, udp: true }
  - { name: ISP2, type: socks5, server: 45.134.93.165, port: 58169, username: 8Z1iLjM1j8l49IO, password: 7zJ14Hco23Fcvcj, udp: true }
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - MODE_SELECT

  - name: MODE_SELECT
    type: select
    proxies:
      - MAIN_SELECT
      - RELAY_TO_ISP
      - ISP_SELECT

  - name: RELAY_TO_ISP
    type: relay
    proxies:
      - MAIN_SELECT
      - ISP_SELECT

  - name: ISP_SELECT
    type: select
    proxies:
      - ISP1
      - ISP2
rules:
  #tandem
  - DOMAIN-SUFFIX,tandem.net,PROXY

  #ipinfo.io测ip
  #- DOMAIN-SUFFIX,ipinfo.io,PROXY

  #必须开通的广告服务
  #google ad services
  - DOMAIN-SUFFIX,googleadservices.com,PROXY
  - DOMAIN-SUFFIX,ad.doubleclick.net,PROXY
  - DOMAIN-SUFFIX,pixel.everesttech.net,PROXY

  #shandian
  - DOMAIN-SUFFIX,shandianpro.com,PROXY

  #bing
  - DOMAIN-SUFFIX,bing.com,PROXY

  #oracle
  - DOMAIN-SUFFIX,oracle.com,PROXY

  #postman
  - DOMAIN-SUFFIX,postman.com,PROXY

  #leetcode
  - DOMAIN-SUFFIX,leetcode.com,PROXY
  - DOMAIN-SUFFIX,leetcode.cn,PROXY

  #chatgpt
  - DOMAIN-SUFFIX,chat.openai.com,PROXY
  - DOMAIN-SUFFIX,openai.com,PROXY

  #tiktok
  - DOMAIN-SUFFIX,tiktokv.com,PROXY
  - DOMAIN-SUFFIX,tiktokcdn.com,PROXY
  - DOMAIN-SUFFIX,tiktokcdn-us.com,PROXY

  #bilibili
  #- DOMAIN-SUFFIX,bilibili.com,PROXY
  #- DOMAIN-SUFFIX,biliapi.net,PROXY
  #- DOMAIN-SUFFIX,akamaized.net,PROXY
  #- DOMAIN-SUFFIX,bilivideo.com,PROXY
  #- DOMAIN-SUFFIX,www.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,s1.hdslb.com,PROXY
  #- DOMAIN-SUFFIX,static.hdslb.com,PROXY
  #- DOMAIN-SUFFIX,upos-hz-mirrorakam.akamaized.net,PROXY
  #- DOMAIN-SUFFIX,data.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,i0.hdslb.com,PROXY
  #- DOMAIN-SUFFIX,api.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,api.live.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,i2.hdslb.com,PROXY
  #- DOMAIN-SUFFIX,i1.hdslb.com,PROXY
  #- DOMAIN-SUFFIX,cm.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,passport.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,api.geetest.com,PROXY
  #- DOMAIN-SUFFIX,static.geetest.com,PROXY
  #- DOMAIN-SUFFIX,passport.bigfun.cn,PROXY
  #- DOMAIN-SUFFIX,passport.biligame.com,PROXY
  #- DOMAIN-SUFFIX,passport.bilicomic.com,PROXY
  #- DOMAIN-SUFFIX,passport.bigfunapp.cn,PROXY
  #- DOMAIN-SUFFIX,passport.bilibili.cn,PROXY
  #- DOMAIN-SUFFIX,passport.bilicomics.com,PROXY
  #- DOMAIN-SUFFIX,api.vc.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,message.bilibili.com,PROXY
  #- DOMAIN-SUFFIX,backup.hdslb.com,PROXY

  #tcl
  - DOMAIN-SUFFIX,tcl.com,DIRECT
  - DOMAIN-SUFFIX,tclking.com,DIRECT

  #默认规则
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400